### ISSUE TITLE
Proposed fingerprint reader setup brakes Ansible

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#106]
If I have

```yaml
fingerprint: True
```

in `group_vars/all` and setup `fprintd` and try to run `ansible-playbook -i localhost playbook.yml --ask-become-pass` I catch the error:

```
<localhost> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1680455171.562048-412582-219023120032225/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "msg": "timeout waiting for privilege escalation password prompt:\n"
}
```

# Workaround

Install and setup `pam_fprintd_grosshack` as suggested in [Arch wiki](https://wiki.archlinux.org/title/Fprint#Login_configuration):

> If you want to prompt for fingerprint and password input at the same time, you can use [pam-fprint-grosshack](https://aur.archlinux.org/packages/pam-fprint-grosshack/). This may be needed for some graphical programs which do not allow blank password input, such as Gnome's built-in polkit agent. 

```
auth		sufficient  	pam_fprintd_grosshack.so
auth		sufficient  	pam_unix.so try_first_pass nullok
...
```

P.S. Also fprintd with `pam_fprintd.so` brakes [yay](https://aur.archlinux.org/packages/yay) AUR helper. And `pam_fprintd_grosshack` fixes it.

**Comment by pigmonkey** [comment]
I don't have a fingerprint reader on my current laptop, so I don't use that option anymore.


Before patching PAM with an AUR package, I'd try setting `pam_unix.so try_first_pass likeauth nullok` as the wiki suggests. That looks like it'd let you first auth with a password and fall back to the fingerprint reader, which I imagine may avoid whatever is causing Ansible to hang.

**Comment by petRUShka** [comment]
Looks like solution from Arch Wiki that you have quoted works good enough. I'll test in couple of weeks.
