### ISSUE TITLE
Grsecurity breaks VirtualBox

### ISSUE THREAD

**Issue by pigmonkey** [pigmonkey/spark#12]
There doesn't seem to be any way around this short of building a custom kernel, which I do not want to do.

I use VirtualBox to spin up a handful of Debian-based images, mostly managed with Vagrant. Switching over to some sort of libvirt/kvm backend may be more productive than trying to get vbox to work.

**Comment by petRUShka** [comment]
Is it true that in current config you cannot use both: Grsecurity kernel and Virtualbox symalteniously?

**Comment by jshuping** [comment]
Yes that is correct, see https://wiki.archlinux.org/index.php/grsecurity#Compatibility

**Comment by pigmonkey** [comment]
Yup. Maybe someday someone will submit a patch to configure libvirt and vagrant...
