### ISSUE TITLE
Grsecurity playbook assumes bootloader is grub

### ISSUE THREAD

**Issue by jshuping** [pigmonkey/spark#14]
On my EFI-based macbook, I'm using systemd-boot (ex gummiboot) instead of grub.

I will have to figure out the steps to actually configure/load/boot the grsec kernel on my laptop.
After running spark, I have /etc/mkinitcpio.d/linux-grsec.preset (in addition to linux.preset).
Running the typical {{mkinitcpio -p linux}} only reads the linux.preset.
I probably also have to update/append to /boot/loader/arch/entries.conf to choose grsec kern from the boot menu.

**Comment by pigmonkey** [comment]
I didn't have to do anything with mkinitcpio. I think the package handles that.

Looking at [the wiki](https://wiki.archlinux.org/index.php/Systemd-boot), I think you need to check if a grsec was added to `$esp/loader/entries/` by the package, then check the default in `$esp/loader/loader.conf`, and then run `bootctl update`.

If the package handles the entries for systemd-boot like it did for grub, we probably just need a handler for `bootctl update`.

**Comment by pigmonkey** [comment]
I'm closing this since I only have experience with grub. If a systemd-boot user finds that we need a `bootctl` handler, I'll accept a patch.
