### ISSUE TITLE
SliM seems not to be maintained and therefore isn't recommended by archlinux

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#29]
Quotation from [archwiki](https://wiki.archlinux.org/index.php/SLiM): 
>  Warning: The SliM project has been abandoned (the project homepage is down, leaving a github mirror), and is not fully compatible with systemd, including logind sessions. Consider using a different Display manager or Xinitrc.

What do toy think about switching to lightdm for example?

**Comment by pigmonkey** [comment]
Thanks for the reminder. At the end of 2015 I looked at most of the alternatives and failed to find anything I liked. Slim has not actually broken yet, so I was happy to stay with it.

I'll try the alternatives again.

**Comment by pigmonkey** [comment]
LightDM seems fine.
