### ISSUE TITLE
Networkmanager: add nmtrust to AUR and install it from aur

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#31]
Posibly it is better to install [nmtrust](https://github.com/pigmonkey/nmtrust) in archway: add it to AUR and install it as AUR package.

**Comment by petRUShka** [comment]
Same question for [firewarden](https://github.com/pigmonkey/firewarden).

**Comment by pigmonkey** [comment]
It is probably more correct, but if I created AUR packages for them I would want to version both scripts. That's more work. Considering that firewarden is a single file, nmtrust is two files, and all 3 files are in locations that do not interfere with any system packages, I don't think there would be much of a benefit for Spark users. I haven't been motivated to overcome my laziness in that regard.
