### ISSUE TITLE
Networkmanager

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#32]
Please, explain why do you add following packages as dependencies for networkmanager:
```
- xfce4-notifyd                                                                                                          
- gnome-keyring 
```

**Comment by pigmonkey** [comment]
Gnome Keyring is required for Network Manager to [encrypt stored passwords](https://wiki.archlinux.org/index.php/NetworkManager#Encrypted_Wi-Fi_passwords).

notifyd is used to [provide notifications](https://wiki.archlinux.org/index.php/NetworkManager#Xfce) when connecting to and disconnecting from networks.
