### ISSUE TITLE
Udisks: why disable automounting and why mount to media?

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#33]
Why do you disable automount? Is it for sequrity reason? If so please give some links where to read about it.

And about `/media`: do you change default behaviour (`/var/ran/media`) just for convinience or there is something else?

```
  5 - name: Disable udisks automounting                                                                                                     
...                                                                    
 11 - name: Mount to /media         
```

**Comment by pigmonkey** [comment]
I dislike automounting. I can never think of a time when I want it. This could easily be made a configurable option, where automount is disabled by default.

I stick to `/media` out of habit. I don't see any benefit to the new location on a single-user system, so I'm not motivated to break my habit.
