### ISSUE TITLE
Unbound

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#34]
Why do you install [unbound](https://wiki.archlinux.org/index.php/Unbound) by default? Could you please point to benefits of it in default distribution?

**Comment by pigmonkey** [comment]
I appreciate having a local DNS server to cache results and to block ad hosts. Unbound is fairly lightweight and simple to run.

It isn't necessary to a functional system, but users who don't want it could just comment out the role or skip the tag.

**Comment by petRUShka** [comment]
@pigmonkey I'm revising Unbound usage right now. On of the reasons: Unbound sometimes prevent captive portal to show up in some WiFi networks.

Please help me to clarify two moments:

1. Since you are moving ad block from unbound to hostctl it is only one reason for unbound to be in setup: local DNS cache. is it true?
2. What are the benefits of local DNS cache? Is it only speed or some other reasons?

P.S. Browsers have their own in-memory DNS cache ([Firefox for example](https://support.mozilla.org/en-US/questions/1258756)).

**Comment by pigmonkey** [comment]
I run Unbound locally primarily for the performance gain from local caching. I do not believe applications like web browsers should have anything to do with DNS. Resolution and caching should happen at the system level, and the results then made available to any application that needs them.
