### ISSUE TITLE
Fonts: Failed to install freetype2-infinality-ultimate

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#36]
The output:

`failed: [localhost] (item=[u'freetype2-infinality-ultimate', u'fontconfig-infinality-ultimate', u'cairo-infinality-ultimate']) => {"failed": true, "item": ["freetype2-infinality-ultimate", "fontconfig-infinality-ultimate", "cairo-infinality-ultimate"], "msg": "failed to install freetype2-infinality-ultimate"}
`

Possible reason: 

`freetype2-infinality-ultimate and freetype2 are in conflict. Remove freetype2?`

**Comment by petRUShka** [comment]
Same for `fontconfig-infinality-ultimate` package.

**Comment by petRUShka** [comment]
And any question by `pacman` force ansible to fail installation. Another example:
  
    gvim and vim are in conflict (vim-minimal). Remove vim? [y/N] 

Is it possible to somehow handle that?

Because it is contradicts with Ansible's idempotent nature...

**Comment by petRUShka** [comment]
It seems that it isn't easy to automate pacman in that way: http://unix.stackexchange.com/questions/274727/how-to-force-pacman-to-answer-yes-to-all-questions

**Comment by pigmonkey** [comment]
This is why the infinality tasks occur before any other graphical tasks (even before the X role). The order of roles in the playbook is important.
