### ISSUE TITLE
Cannot install cower

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#40]
There is absolutely fresh arch linux install (real hardware not virtual).

There is an error during installing cower:

```
TASK [base : Install cower] ****************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "failed to install package cower, because: ==> ERROR: Cannot find the strip binary required for object file stripping.\n"}
	to retry, use: --limit @/home/petrunin/tmp/spark/playbook.retry
```

Reason is missed `binutils` package.

**Comment by petRUShka** [comment]
There is also missed `make` package and `cc` . My solution is to preinstall all `base-devel` group.

**Comment by pigmonkey** [comment]
`base-devel` is installed as part of the pacstrap in [INSTALL.md](https://github.com/pigmonkey/spark/blob/master/INSTALL.md).

However, we can include it in the base packages for redundancy.
