### ISSUE TITLE
Editors: failed to install gvim

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#41]
In absolutely fresh system there is preinstall `vim` package, so installation of gvim always break the execution of playbook:

```
:: gvim and vim are in conflict (vim-minimal). Remove vim? [y/N]
```

**Comment by pigmonkey** [comment]
That's new. Do you know what package is including vim as a dependency?

**Comment by petRUShka** [comment]
Possibly you are right. May be i've installed it during installation of arch linux.
