### ISSUE TITLE
harfbuzz update + Infinality breaking System 

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#43]
Quotation from [fix-infinality.md](https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671):

> If you installed infinality-bundle or the patched freetype2-infinality(-ultimate) package, you'll most likely recently have run into an error relating to the harfbuzz package (>= 1.4.1-1), specifically something like: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates.

So there is a problem which break a lot of processes like compilation for example.

```
CC -o dwm
/usr/lib/libharfbuzz.so.0: undefined reference to `FT_Get_Var_Blend_Coordinates'
collect2: error: ld returned 1 exit status
make: *** [Makefile:29: dwm] Error 1
```

Literature by this topic:

1. Workaround: https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671
2. Reddit discussion: https://www.reddit.com/r/archlinux/comments/5mphpu/psa_harfbuzz_update_infinality_breaking_system/
3. Another discussion in github issuses: https://github.com/jaagr/polybar/issues/310

**Comment by pigmonkey** [comment]
I had a feeling that Infinality's days were numbered. That's unfortunate. We'll have to rip it out.

**Comment by petRUShka** [comment]
Found on [arch wiki](https://wiki.archlinux.org/index.php/Infinality):

> Infinality is dead both upstream and with the downstream maintainer bohoomil (e.g. [1]), and differences with freetype upstream become small as development progresses (see "news & updates" on [2]). Additionally, the recent update of harfbuzz to 1.4.1-1 is incompatable with freetype2-infinalityAUR which leads to breakage of multiple packages (deluge and vlc to name a few). See this link for instructions to get back nice looking fonts using the supported freetype2 natively.

**Comment by pigmonkey** [comment]
I've pushed the changes, minus the substitutions that I'm still playing with.

The only screwy thing I've noticed so far is that the new freetype caused changes to how Terminus is referenced.

https://github.com/pigmonkey/dotfiles/commit/caed20b649753f5855107592d75f6e26140d50a8

https://bbs.archlinux.org/viewtopic.php?id=221794

**Comment by pigmonkey** [comment]
Somebody let me know if there are changes to the [fix](https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671) or [substitution](https://gist.github.com/cryzed/4f64bb79e80d619866ee0b18ba2d32fc) gists.
