### ISSUE TITLE
SSD support: enabling TRIM on all levels

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#47]
According to article [How to properly activate TRIM for your SSD on Linux: fstrim, lvm and dm-crypt](http://blog.neutrino.es/2013/howto-properly-activate-trim-for-your-ssd-on-linux-fstrim-lvm-and-dmcrypt/)

TRIM should be enabled in all configs expect for fstab: 

1. /etc/crypttab
2. /etc/lvm/lvm.conf

Quote:

> you must enable support for TRIM in these three layers: The filesystem, LVM and dm-crypt. There is no point in enabling it at the filesystem level if you don’t enable it also on the other layers. The TRIM command should be translated from one layer to another until reaching the SSD.

But according to [spark](https://github.com/pigmonkey/spark/blob/master/roles/ssd/tasks/main.yml) there isn't any setup like this.

**Comment by pigmonkey** [comment]
This seems incorrect.

In the GRUB section of the install guide, we include the `allow-discards` option. This is the only thing that is needed for the dm-crypt layer. You would modify `/etc/crypttab` if you use a non-root filesystem. We don't.

According to the comments in `/etc/lvm/lvm.conf`, issue discards is only used there when you are modifying the logical volume (ie `lvremove` or `lvreduce`). It is not necessary to enable that to enable TRIM for our daily user space activities (ie `rm`).

In the SSD role we detect if TRIM support exists. If it does, we enable the weekly `fstrim` timer.

I don't think anything else is required. I could be wrong, but that's my reading. Is there a way to test if this is actually working? Doing something like `fstrim /home` returns success, which seems positive.

**Comment by petRUShka** [comment]
There is an article in Arch Wiki with [Discard/TRIM support for solid state drives (SSD)](https://wiki.archlinux.org/index.php/Dm-crypt/Specialties#Discard.2FTRIM_support_for_solid_state_drives_.28SSD.29) section.

It stated: 

> In linux 3.1 and up, support for dm-crypt TRIM pass-through can be toggled upon device creation or mount with dmsetup. Support for this option also exists in cryptsetup version 1.4.0 and up. To add support during boot, you will need to add :allow-discards to the cryptdevice option.

> Besides the kernel option, it is also required to periodically run fstrim or mount the filesystem (e.g. /dev/mapper/root in this example) with the discard option in /etc/fstab

So possibly you are right and GRUB is enough (compared to have a /etc/crypttab modified).

**Comment by petRUShka** [comment]
But speaking about LVM. There is another article: [Solid_State_Drives#LVM](https://wiki.archlinux.org/index.php/Solid_State_Drives#LVM). Quotation:

>  Note: Enabling this option will "issue discards to a logical volumes's underlying physical volume(s) when the logical volume is no longer using the physical volumes' space (e.g. lvremove, lvreduce, etc)" (see lvm.conf(5) and/or inline comments in /etc/lvm/lvm.conf). As such it does not seem to be required for "regular" TRIM requests (file deletions inside a filesystem) to be functional.

So it should not affect `fstrim` run but should affect lvm-based changes.

P.S. According to [debian wiki](https://wiki.debian.org/SSDOptimization#Mounting_SSD_filesystems) an alternative to LVM's "issue_discards" is to `blkdiscard` on the LV before `lvremove`, or afterwards on a temporarily created LV with `lvcreate -l100%FREE` to trim all unused LVM space.

**Comment by pigmonkey** [comment]
So the only thing we are potentially missing is the LVM option, which only comes into play when resizing of removing logical volumes. I'd rather not touch the LVM config without a good reason. It seems unnecessary in this case (I've never used those tools), especially since there are easy alternatives.
