### ISSUE TITLE
Tuning SSD: improve expected lifetime and increase performance of the whole system

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#48]
There are several articles on the subject. I mention some of them:
- [LinuX, SSDs and disk encryption](http://blog.mfhs.eu/2013/09/15/linux-ssds-and-disk-encryption/)
- Arch wiki [Improving_performance#Storage_devices](https://wiki.archlinux.org/index.php/Improving_performance#Storage_devices) 
- [Debian SSDOptimization](https://wiki.debian.org/SSDOptimization)

1. Main advice is to reduce of SSD write frequency via RAMDISK ([debian](https://wiki.debian.org/SSDOptimization#Reduction_of_SSD_write_frequency_via_RAMDISK), [arch](https://wiki.archlinux.org/index.php/Improving_performance#Reduce_disk_reads.2Fwrites) and "After installation — Setting up ramdisks using tmpfs" from blog post). Some quotations are followed.

    Blog:
    > good paradigm is to use ramdisks for temporary files to avoid wasting writes for files we don't want to keep anyway. Looking at the UNIX Filesystem Hierarchy Standard we note that temporary files are stored at /tmp and (in practice to a lesser extent) at /var/tmp. Moving the files in these locations to RAM can now be easily achieved by mounting the corresponding paths with the filesystem type tmpfs. This will create a dynamical ramdisk, meaning that only as much RAM is used up by the disk as it requires to store the files

    > If you can spare a little more RAM you should furthermore consider the use of ramdisks for locations in the file system tree where frequent writes take place, e.g. /var/log and /var/spool. You might be aware that /var/log contains the system's logfiles, meaning that by applying these settings you will loose all logs on system reboot. For servers this would surely be a problem, but in the case of laptops I don't want to loose this option of saving a lot of writes.

    Arch:
    > Avoiding unnecessary access to slow storage drives is good for performance and also increasing lifetime of the devices, although on modern hardware the difference in life expectancy is usually negligible. 

2. Another but controversial common advice is to [switch to low-latency IO-Scheduler](https://wiki.debian.org/SSDOptimization#Low-Latency_IO-Scheduler):

    > The default I/O scheduler queues data to minimize seeks on HDDs, which is not necessary for SSDs. Thus, use the "deadline" scheduler that just ensures bulk transactions won't slow down small transactions

    Blog post (After installation — Changing the disk scheduler) is also saying that:

    > The disk scheduler controls how the kernel schedules access to storage drives. For rotating disks data access is obviously a slow process and it needs to be distributed fairly between the many processes that might want to read or write something to/from different parts of the disk. The default scheduler called cfq is optimised for the latter scenario, but not for SSDs. Performance can be greatly improved if noop or deadline are used instead. Noop is the most simple one: It basically handles requests in the order they are submitted. Deadline in some sense implements a timer on top and stops requests that take too long. Which one to use pretty much depends on the underlying hardware and the use case, but for a normal laptop and a normal use it should not make much of a difference. 

    [Arch wiki](https://wiki.archlinux.org/index.php/Improving_performance#Tuning_IO_schedulers) warns us:

    > Only the CFQ scheduler supports setting IO priorities with ionice. Some background processes rely on this capability to perform background IO unobtrusively by reducing their IO priority, for example KDE's file indexer baloo. Using a different scheduler than the default CFQ scheduler can worsen the user experience on desktops. 

3. One more controversial option is adding the mount options noatime and nodiratime. See (Blog: After installation — Editing /etc/fstab, [arch](https://wiki.archlinux.org/index.php/Fstab#atime_options) and [debian](https://wiki.debian.org/SSDOptimization#Mounting_SSD_filesystems))

    Blog:

    > For each partition that is located on an SSD drive you should at least add the mount options noatime and nodiratime. These options will suppress the usual bookkeeping of access times for files and directories, respectively. Usually accessing a file implies a write as well since the current date and time will be written to the so-called inode table of the filesystem. For most applications this is not required and can therefore be safely disabled using the above options.

    Arch:
    > The noatime option is known to improve performance of the filesystem.

    Debian:
    > Add the "noatime" (or "relatime") mount option in /etc/fstab, to disable (or significantly reduce) disk writes whenever a file is read. Please note that since Linux kernel 2.6.30, "relatime" is the default. This improves filesystem read performance for both SSDs and HDDs. 

4. Blog: Enabling device-level write cache

    > Turning on the write cache of a drive causes the drive to use some internal RAM to cache files until they are written to the disk properly. This improves performance in both SSDs as well as traditional hard drives. A disadvantage is that in the case of an abrupt power loss enabling this feature could lead to data loss. Since data is usually only kept in the disk cache for extremely short times this is hardly a problem for normal use cases.

5. Move browsers cache (or even whole browser or other software profiles) to RAM.

    Blog:

    > On a user level it is mostly the browser cache which is very predictable to cause a lot of writes. Now that /tmp is located in RAM it is a good idea to make the browser drop its cache at this location

    Move full browser profile to RAM and sync: https://wiki.archlinux.org/index.php/Profile-sync-daemon

    > Since the profile(s), browser cache*, etc. are relocated into tmpfs (RAM disk), the corresponding I/O associated with using the browser is also redirected from the physical drive to RAM, thus reducing wear to the physical drive and also greatly improving browser speed and responsiveness. 

    [Arch#Relocate files to tmpfs](https://wiki.archlinux.org/index.php/Improving_performance#Relocate_files_to_tmpfs) provides following options:

    > Relocate files, such as your browser profile, to a tmpfs file system, for improvements in application response as all the files are now stored in RAM:
    > 
    >     1. Refer to Profile-sync-daemon for syncing browser profiles. Certain browsers might need special attention, see e.g. Firefox on RAM.
    >     2. Refer to Anything-sync-daemon for syncing any specified folder.
    >     3. Refer to Makepkg#tmpfs for improving compile times when building packages.

**Comment by pigmonkey** [comment]
None of this appeals to me.

I don't think modern SSDs have a short enough life to justify jumping through extra hoops to extend it. As mentioned in the quote from the Arch wiki, the effect is negligible.

Arch [defaults](https://wiki.archlinux.org/index.php/Tmpfs) to mounting `/tmp` as a tmpfs, which makes sense. Using a tmpfs for `/var/log` does not makes sense. Loosing logs is unreasonable, even on a laptop.

Noting when a file is accessed is useful, and sometimes required -- `noatime` breaks Mutt.

I can see the appeal in moving parts of the browser to a tmpfs, but I'd rather leave that up to the user. A significant portion of my browsing is done through browsers in firewarden, which means their profiles and cache are in `/tmp` which, as previously mentioned, is already a tmpfs. The only thing Spark would do to support profile-sync-daemon is install a single package, so I think it's fine to let the user do this if they want it. They could even add it to  `aur.packages` in their config.
