### ISSUE TITLE
zathura and firejail brken synctex functionality (backward search)

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#49]
[About](https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#L1998) synctex and `backward search` functionality:

> Synctex is a tool that enables synchronization of the text editor position and
> the pdf viewer position.  The tool may be used to add mappings in vim to go to
> the current position in the compiled pdf document (forward search), and also
> to go from a specific position in the pdf file to the corresponding position
> in vim (inverse/backward search).
> ...
> In supported viewers one may set up backward or inverse search.  When
> correctly set up, this allows one to go directly from a selected line in the
> viewer (typically by double clicking with the mouse or something similar) to
> the corresponding line inside the VIM instance. 

For example I'm using vim (+[vimtex](https://github.com/lervag/vimtex)) and zathura together. Zathura should be able to run vim like this: `vim --servername VIM --remote +10 my-file.tex` to force VIM to place cursor on line 10.

It is prohibited in spark defaults because in default zathura.profile there isn't vim binary at all. The solution is to add this line: `private-bin zathura,vim`

P.S. Possibly it should be a little bit agile and support any editor binary not only VIM.

**Comment by pigmonkey** [comment]
I think it's better to let the user do this in their profile if they want the feature. That way they can whitelist whatever edit they want, and we can still ship a locked-down profile by default. You would do this by create a `~/.config/firejail/zathura.profile` file that sourced the Spark-provided profile and appended the `private-bin` line.

    include /usr/local/etc/firejail/zathura.profile
    private-bin zathura,vim

I do this myself when I want to tweak a profile in a way that doesn't seem appropriate to include in Spark -- usually for setting up private home dirs.

https://github.com/pigmonkey/dotfiles/tree/master/config/firejail
