### ISSUE TITLE
VirtualBox not working due to missing headers

### ISSUE THREAD

**Issue by chopmann** [pigmonkey/spark#53]
I had to add the linux-header packages to the base packages.
Was this really missing or did i made a configuration mistake?
Grepping the source from github didnt yield a result.

**Comment by pigmonkey** [comment]
VirtualBox does not work because Spark uses the grsec kernel. This breaks VirtualBox regardless of whether the headers are installed or not (however, we do install `linux-grsec-headers`). See #12.
