### ISSUE TITLE
cower fails to install

### ISSUE THREAD

**Issue by sudoforge** [pigmonkey/spark#59]
`cower` fails to install due to a missing dependency, `yajl`.

**Comment by pigmonkey** [comment]
AUR packages are installed via `makepkg` using the `-s` option, which uses pacman to install missing dependencies. Dependencies which are AUR packages can't be installed with pacman, so we do have to explicitly install those, but yajl is in the official repos. So your pull request should be unnecessary.

Can you share the exact error you encountered on the cower task?

It may have been a networking issue, where pacman just temporarily failed to find the yajl package. We used to have a similar issue where the macchiato task would cause networking services to bounce. Ansible would move on to the next package installation task before networking was brought back up, causing pacman to error out. I don't think there is anything like that in the base role currently, but I'm not sure what else would cause the cower install to fail.

**Comment by sudoforge** [comment]
I was actually in a bit of a rush that morning, and didn't think to log the error. I re-ran the role a couple times, and after repeated failures, simply installed the dependency myself. I'll see if I can recreate that this evening.

**Comment by sudoforge** [comment]
I've confirmed that this was due to a temporary network connectivity issue.
