### ISSUE TITLE
Cower fails to install 

### ISSUE THREAD

**Issue by chrisvel** [pigmonkey/spark#62]
This is the information I have about the error: 

```
fatal: [host1]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "dir": null, 
            "name": "cower", 
            "skip_pgp": true, 
            "user": "someone"
        }
    }, 
    "msg": "failed to install package cower, because: ==> Making package: cower 17-2 (Thu Oct 19 14:09:03 EEST 2017)\n==> Checking runtime dependencies...\n==> Checking buildtime dependencies...\n==> Retrieving sources...\n  -> Found cower-17.tar.gz\n  -> Found cower-17.tar.gz.sig\n==> WARNING: Skipping verification of source file PGP signatures.\n==> Validating source files with md5sums...\n    cower-17.tar.gz ... Passed\n    cower-17.tar.gz.sig ... Skipped\n==> Extracting sources...\n  -> Extracting cower-17.tar.gz with bsdtar\n==> Removing existing $pkgdir/ directory...\n==> Starting build()...\n/bin/sh: pod2man: command not found\nmake: *** [Makefile:90: cower.1] Error 127\n==> ERROR: A failure occurred in build().\n    Aborting...\n"
}
```
I have also tried to install via yaourt and I get an error about PGP signatures:

```
ERROR: One or more PGP signatures could not be verified!
ERROR: Makepkg was unable to build cower
```

It seems like a cower issue and not spark's.

**Comment by pigmonkey** [comment]
It is failing to find `pod2man`, which is located at `/usr/bin/core_perl/pod2man` and provided by the perl package.

I think your `$PATH` is screwy. Check if `/usr/bin/core_perl` is present in it. This is done automatically by the perl package through `/etc/profile.d`, but you may have overwritten it in your shell config files.

**Comment by chrisvel** [comment]
The path is there and I can install it via ssh. Do you think it has something to do the fact that I am installing it to Antergos instead of Manjaro or simply Arch?

**Comment by chrisvel** [comment]
cower installs fine with Manjaro but fails due to PGP error in Antergos. I don't know why to be honest, it seems that they have different versions in yaourt/aur packages. I am closing this and I hope to help someone else that has been consumed a lot of time to make this work !

The solution was to change ansible-aur (that uses cower but also curl - not sure why this didn't work) to something like this: 
```
- name: Install AUR base packages
  become: yes
  become_user: "{{ user.name }}"
  command: yaourt -S {{ item }} --noconfirm --needed
  with_items: "{{ aur.packages }}"
  tags:
    - aur
    - packages
```
