### ISSUE TITLE
Broken pipe in pacman and aur

### ISSUE THREAD

**Issue by chrisvel** [pigmonkey/spark#63]
I am using the spark repo to configure a laptop of mine.

Unfortunately I am getting these kind of messages in pacman and aur:

    <192.168.1.2> (0, '', 'OpenSSH_7.6p1, OpenSSL 1.1.0f  25 May 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: 
    auto- mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: 
    mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: 
    mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 7263\r\ndebug3: mux_client_request_session: session 
    request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r
    \ndebug2: Received exit status from master 0\r\n')

Then the shell halts and after 3-4 minutes it fails. The system I am trying to deploy is a clean install of the latest Manjaro O/S. Not every role it has fails - I have commended everything out in order to find why this error happens. The OpenSSH server has the default configuration, so nothing fancy here.

I am not sure this issue is of this repo's fault, just posting it there in case someone else has the same. I've seen some issues as well in ansible's repository for 2.4. Please ignore and close If that's the case.

**Comment by jshuping** [comment]
Glad you are using spark! I have not seen that error before.  It kinda looks like you are ssh'ing with -v to enable debug mode, and that debug output is making something else unhappy? Just a wild guess.

**Comment by chrisvel** [comment]
Not at all, I've tried with -vvvv and without any -v's but no hope.

**Comment by pigmonkey** [comment]
I've never experienced this. I've also never ran spark on anything other than localhost, but there's no reason it shouldn't work.

The errors appear to be somehow related to ssh multiplexing. Do you have an entry in `~/.ssh/config` on the host running Ansible that sets any of the various `Control*` options for the remote host? Does `/etc/ssh/sshd_config` on the remote host have any session limiting options like `MaxSessions` or `MaxStartups`?

Have you tried flipping Ansible's [`pipelining`](http://docs.ansible.com/ansible/latest/intro_configuration.html#pipelining) bit?

**Comment by chrisvel** [comment]
@pigmonkey yes, I've tried everything I found in the web regarding to similar errors. I don't have a config file for ssh. I downgraded to ansible 2.3 and I don't seem to have this problem, except an error for AUR packages that fail because of missing dependencies. I know this is not related to the above but did it happen to you? 

I have opened a bug in official ansible github repo for 2.4 and I am waiting for any replies.

**Comment by pigmonkey** [comment]
Pacman is able to install dependencies of AUR packages from the official repositories, but not other dependencies that are themselves AUR packages. For those dependencies, we need to specify the packages explicitly in the task so that they are installed separately.

Occasionally the dependencies of an AUR package change to include additional AUR packages, so its possible we are missing some. Which packages are failing for you?

**Comment by chrisvel** [comment]
@pigmonkey https://github.com/ansible/ansible/issues/32177

Some of them, for example _dnsenum_.

**Comment by pigmonkey** [comment]
That package is not installed by spark.

If you have created a role for it or added it to the `aur.packages` var in your fork, you will have to also include its two perl dependencies from the AUR (`perl-net-netmask` and `perl-string-random`).

When we install an AUR package, basically all we are doing is downloading the PKGBUILD and running `makepkg -sri`. You can see how we handle AUR dependencies by looking at, for example, [the Kiwix role](https://github.com/pigmonkey/spark/blob/master/roles/kiwix/tasks/main.yml)

**Comment by chrisvel** [comment]
How did you find these specific dependencies? I am using `pacman -Qi dnsenum` and it returns `Depends On  : perl  perl-net-dns  perl-net-ip  perl-net-netmask  perl-string-random  perl-xml-writer`.  There are also other ones like _tilix_.

**Comment by pigmonkey** [comment]
When you ask pacman for the dependencies, it is just reading the `depends` array in the PKGBUILD, which is just a list of package names. It doesn't know or care where those packages are, until it tries to grab one and fails.

In this case I just visited the AUR package page and looked at which dependencies linked to the AUR. That's not necessarily the complete picture, since those dependencies could have further AUR dependencies.

Most AUR helpers will figure out which dependencies are AUR packages, so you may be able to use that as a guide when you are building out your tasks. For example, aura splits them:

    $ aura -A dnsenum
    [sudo] password for pigmonkey:
    aura >>= Determining dependencies...
    aura >>= Repository dependencies:
    perl-module-build
    perl-net-dns
    perl-net-ip
    perl-xml-writer

    aura >>= AUR Packages:
    dnsenum
    perl-net-netmask
    perl-string-random

    aura >>= Continue? [Y/n]

**Comment by chrisvel** [comment]
Thanks a lot. I will close the issue as it seems that it's something about ansible and how it makes SSH connections. It works with ansible 2.3 with SSH or 2.4 and paramiko. For those having the same issue they can follow the link to Ansible issue above.
