### ISSUE TITLE
replace rcm with dotbot

### ISSUE THREAD

**Issue by dummys** [pigmonkey/spark#64]
Hi,

RCM is no more supported, why not replace it with : [dotbot](https://github.com/anishathalye/dotbot) ?

**Comment by pigmonkey** [comment]
Can you share their end of life notice? The RCM repository looks active -- at least as active as I would expect for a tool that is effectively complete.

**Comment by dummys** [comment]
You are right, I was looking at the aur repo in fact: https://aur.archlinux.org/packages/rcm/

Anyway I would like to thank you for spark, I learned a lot of new technics/tools from it.
