### ISSUE TITLE
pasystray-gtk3-standalone has been removed from the AUR.

### ISSUE THREAD

**Issue by sudoforge** [pigmonkey/spark#68]
Hey there - I have a fork of yours under development, and noticed that `pasystray-gtk3-standalone` has been removed from the AUR. You use it [in the `sound` role][0], figured a heads up wouldn't hurt.

[0]: https://github.com/pigmonkey/spark/blob/master/roles/sound/tasks/main.yml#L18

**Comment by pigmonkey** [comment]
Thanks. It looks like we'll need to move to the git package.
