### ISSUE TITLE
sshd.socket not available anymore

### ISSUE THREAD

**Issue by crulie** [pigmonkey/spark#92]
Hi, I'm trying out this playbook. 

I'm having issues with the ssh role. It seems that sshd.socket is not available in the openssh package anymore?

I suppose the role has to be updated with using sshd.service instead? 

Best regards,
Daniel

**Comment by pigmonkey** [comment]
Yeah, looks like it was removed. I'll update the role.

https://bugs.archlinux.org/task/62248
