### ISSUE TITLE
Pipewire instead of Pulseaudio

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#95]
Don't you think on moving to [Pipewire](https://pipewire.org/)?

From [Arch Wiki](https://wiki.archlinux.org/title/PipeWire):

> PipeWire is a new low-level multimedia framework. It aims to offer capture and playback for both audio and video with minimal latency and support for PulseAudio, JACK, ALSA and GStreamer-based applications. 

From [Wikipedia](https://en.wikipedia.org/wiki/PipeWire):

> PipeWire has received much praise, especially among the GNOME and Arch Linux communities. Particularly, it fixes many problems that PulseAudio had experienced, including its high CPU usage, Bluetooth connection issues, and its JACK backend issues. 

From official wiki, [How Is PipeWire Supposed To Be A Better PulseAudio?](https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/FAQ#how-is-pipewire-supposed-to-be-a-better-pulseaudio):

> PipeWire can achieve lower latency with much less CPU usage and dropouts compared to PulseAudio. This would greatly improve video conferencing apps, like WebRTC in the browser.
> PipeWire's security model can stop applications from snooping on each other's audio.
> PipeWire allows more control over how applications are linked to devices and filters.
> PipeWire uses an external policy manager that can provide better integration with the rest of the desktop system and configuration.

Even [Pulseeffects](https://github.com/wwmm/pulseeffects) migrated to PipeWire.

So it seems like good idea to try it.

**Comment by pigmonkey** [comment]
I've been vaguely following Pipewire's progress, but have yet to try it. It sounds like it still has some issues -- bluetooth connectivity edge cases, stuttering in some applications when switching outputs, etc. I assume it will be the future, but I'm happy to wait it out while they fix their bugs since I have zero issues with Pulse today.

**Comment by jshuping-ns1** [comment]
https://www.redpill-linpro.com/techblog/2021/05/31/better-bluetooth-headset-audio-with-msbc.html

**Comment by jshuping** [comment]
https://www.redpill-linpro.com/techblog/2021/05/31/better-bluetooth-headset-audio-with-msbc.html

**Comment by brett** [comment]
I think making pipewire or pulse a configurable option is the right solution
